import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import { link } from 'fs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    "README",
    {type: 'autogenerated', dirName: 'api-docs'},
    {type: "link", label: "Ecosystem", href: "/ecosystem", description: "Libraries and tools for the the F# web ecosystem.", className: "menu-link--success menu-link--community"}
  ],

  ecoSidebar: [{type: 'autogenerated', dirName: 'ecosystem'}]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
